apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
      - name: admin-frontend
        image: cna-admin-fe:0.2
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend
  labels:
    app: admin-frontend
spec:
  type: NodePort
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      name: http
