apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-frontend
  template:
    metadata:
      labels:
        app: prod-frontend
    spec:
      containers:
      - name: prod-frontend
        image: cna-prod-fe:0.2
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: prod-frontend
  labels:
    app: prod-frontend
spec:
  type: NodePort
  selector:
    app: prod-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      name: http