apiVersion: v1
kind: Route
metadata:
  name: prod-backend
spec:
  host: www.cna.com
  path: /api
  port:
    targetPort: http
  to:
    kind: Service
    name: prod-backend
    wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: prod-frontend
spec:
  host: www.cna.com
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: prod-frontend
    wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: admin-backend
spec:
  host: admin.cna.com
  path: /api
  port:
    targetPort: http
  to:
    kind: Service
    name: admin-backend
    wildcardPolicy: None
---
apiVersion: v1
kind: Route
metadata:
  name: admin-frontend
spec:
  host: admin.cna.com
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: admin-frontend
    wildcardPolicy: None